# Generated by Django 2.2.4 on 2023-06-13 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filling', models.CharField(max_length=255)),
                ('crust', models.CharField(max_length=255)),
                ('value', models.IntegerField(default=0, max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pies', to='login.User')),
            ],
        ),
    ]
