# Generated by Django 2.2.4 on 2023-06-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20230613_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('start_data', models.DateField()),
                ('end_data', models.DateField()),
                ('user_join_to_trip', models.ManyToManyField(related_name='user_join_to_trip', to='login.User')),
            ],
        ),
    ]
